# =============================================================================
# BeeWAF â€” Service pour cluster DPC
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: beewaf-svc
  namespace: beewaf
  labels:
    app: beewaf
spec:
  selector:
    app: beewaf
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
